/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Keith' at '10/01/15 16:54' with Gradle 2.2.1
 *
 * @author Keith, @date 10/01/15 16:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
